development:
  adapter: postgresql
  encoding: utf8
  database: mess_dev
  host: localhost
  pool: 5
  username: postgres
  password: password


production:
  adapter: postgresql
  encoding: utf8
  database: mess_prod
  host: localhost
  pool: 5
  username: postgres
  password: password
